# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.4 on 2017-08-27 04:12
=======
# Generated by Django 1.11.4 on 2017-08-25 00:19
>>>>>>> 13cf9dfe51ae403ce3933770d0dfaa02f3e02c9c
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
<<<<<<< HEAD
                ('text', models.TextField()),
=======
>>>>>>> 13cf9dfe51ae403ce3933770d0dfaa02f3e02c9c
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
